<a href="https://colab.research.google.com/github/Siva290822/ICP3/blob/main/Copy_of_ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
vector = np.random.randint(1, 21, 15)
print("Original Vector:\n", vector)

reshaped = vector.reshape(3, 5)
print("\nReshaped Array (3x5):\n", reshaped)

print("\nShape of Array:", reshaped.shape)

for i in range(reshaped.shape[0]):
    max_index = reshaped[i].argmax()
    reshaped[i][max_index] = 0

print("\nModified Array (max in each row replaced with 0):\n", reshaped)


Original Vector:
 [15 17  7 14  7 13  7 15 16  1 20 17 17  7 18]

Reshaped Array (3x5):
 [[15 17  7 14  7]
 [13  7 15 16  1]
 [20 17 17  7 18]]

Shape of Array: (3, 5)

Modified Array (max in each row replaced with 0):
 [[15  0  7 14  7]
 [13  7 15  0  1]
 [ 0 17 17  7 18]]


In [ ]:
array_2d = np.zeros((4, 3), dtype=np.int32)
print("2D Array:\n", array_2d)
print("Shape:", array_2d.shape)
print("Type:", type(array_2d))
print("Data Type:", array_2d.dtype)


2D Array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data Type: int32


In [ ]:
matrix = np.array([[3, -2],
                   [1,  0]])

eig_vals, eig_vecs = np.linalg.eig(matrix)
print("Eigenvalues:", eig_vals)
print("Right Eigenvectors:\n", eig_vecs)


Eigenvalues: [2. 1.]
Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [ ]:
arr = np.array([[0, 1, 2],
                [3, 4, 5]])
diagonal_sum = np.trace(arr)
print("Sum of diagonal elements:", diagonal_sum)


Sum of diagonal elements: 4


In [ ]:
original = np.array([[1, 2],
                     [3, 4],
                     [5, 6]])

reshaped = original.reshape(2, 3)
print("Reshaped Array (2x3):\n", reshaped)


Reshaped Array (2x3):
 [[1 2 3]
 [4 5 6]]
